name: Build FastDDS

on:
  workflow_dispatch:

jobs:
  fastdds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set-up dependancies
      run: |
        codename=$(lsb_release -c -s)
        echo "deb [trusted=yes] https://alest-software.github.io/ubuntu ${codename} main" | sudo tee /etc/apt/sources.list.d/alest-software.list
        sudo apt update
        sudo apt install -y cmake g++ python3-pip wget git
        sudo apt install -y libasio-dev libtinyxml2-dev
        sudo apt install -y libssl-dev
        sudo apt install -y libp11-dev
        sudo apt install -y softhsm2
        sudo apt install -y libengine-pkcs11-openssl
        sudo apt install -y libfoonathan-memory-dev
        sudo apt install -y libfastcdr
        #p11-kit list-modules
        #openssl engine pkcs11 -t

    - name: Build
      run: |
        mkdir build
        cd build
        ARCH=$(dpkg --print-architecture)
        cmake -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=${ARCH} -DCPACK_DEBIAN_PACKAGE_REVISION=${GITHUB_RUN_NUMBER} ..
        cmake --build .
        cpack

