name: Build FastDDS

on:
  workflow_dispatch:

jobs:
  fastdds:
    runs-on: ubuntu-latest

    steps:
    - name: Set-up dependancies
      run: |
        echo "deb [trusted=yes] https://alest-software.github.io/ubuntu noble main" | sudo tee /etc/apt/sources.list.d/alest-software.list
        sudo apt update
        sudo apt install -y cmake g++ python3-pip wget git
        sudo apt install -y libasio-dev libtinyxml2-dev
        sudo apt install -y libssl-dev
        sudo apt install -y libp11-dev
        sudo apt install -y softhsm2
        sudo apt install -y libengine-pkcs11-openssl
        sudo apy install -y fast-cdr
        p11-kit list-modules
        openssl engine pkcs11 -t
