name: Build Fast-DDS

on:
  workflow_dispatch:

jobs:
  FastDDS:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [ubuntu-24.04]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set-up dependancies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ python3-pip wget git
        sudo apt install -y libasio-dev libtinyxml2-dev
        sudo apt install -y libssl-dev
        sudo apt install -y libp11-dev
        sudo apt install -y softhsm2
        sudo apt install -y libengine-pkcs11-openssl
        p11-kit list-modules
        openssl engine pkcs11 -t
